netgen_layouts:
    resource: "@NetgenBlockManagerBundle/Resources/config/routing.yml"
    prefix: "%netgen_layouts.route_prefix%"

netgen_content_browser:
    resource: "@NetgenContentBrowserBundle/Resources/config/routing.yml"
    prefix: "%netgen_content_browser.route_prefix%"

netgen_layouts_contentful:
    resource: "@NetgenContentfulBlockManagerBundle/Resources/config/routing.yml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
