netgen_block_manager:
    resource: "@NetgenBlockManagerBundle/Resources/config/routing.yml"
    prefix: "%netgen_block_manager.route_prefix%"

netgen_content_browser:
    resource: "@NetgenContentBrowserBundle/Resources/config/routing.yml"
    prefix: "%netgen_content_browser.route_prefix%"

netgen_block_manager_contentful:
    resource: "@NetgenContentfulBlockManagerBundle/Resources/config/routing.yml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
